name: Gatsby Publish

on:
  push:
    branches:
<<<<<<< HEAD
      - master
=======
      - dev
>>>>>>> 366bdb8bc215503df0ee54e60b887007afb44001

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
<<<<<<< HEAD
          deploy-branch: gh-pages
#           gatsby-args: --prefix-paths
#           skip-publish: true
=======
>>>>>>> 366bdb8bc215503df0ee54e60b887007afb44001
